package reputation

import (
	"time"

	"github.com/semp-dev/semp-go/keys"
)

// AbuseCategory classifies the nature of a reported abuse incident
// (REPUTATION.md §3.4, ERRORS.md §9).
type AbuseCategory string

// Defined abuse categories.
const (
	AbuseSpam          AbuseCategory = "spam"
	AbuseHarassment    AbuseCategory = "harassment"
	AbusePhishing      AbuseCategory = "phishing"
	AbuseMalware       AbuseCategory = "malware"
	AbuseProtocolAbuse AbuseCategory = "protocol_abuse"
	AbuseImpersonation AbuseCategory = "impersonation"
	AbuseOther         AbuseCategory = "other"
)

// AbuseReport is a SEMP_ABUSE_REPORT message generated by a recipient
// (or a recipient's home server on the user's behalf) about an envelope
// they consider abusive.
//
// The report carries the postmark and seal of the offending envelope as
// evidence. Decrypted brief or enclosure content MUST NOT be included
// without the explicit signed authorization of the affected user
// (REPUTATION.md §3.7).
type AbuseReport struct {
	// Category classifies the abuse.
	Category AbuseCategory `json:"category"`

	// Description is an optional human-written explanation.
	Description string `json:"description,omitempty"`

	// EnvelopeID is the postmark.id of the offending envelope.
	EnvelopeID string `json:"envelope_id"`

	// SubjectDomain is the from_domain of the offending envelope.
	SubjectDomain string `json:"subject_domain"`

	// ReportedAt is the time the report was generated.
	ReportedAt time.Time `json:"reported_at"`

	// AuthorizedDisclosure, if non-nil, indicates that the user has
	// explicitly signed authorization for decrypted content to be included
	// in this report.
	AuthorizedDisclosure *DisclosureAuthorization `json:"authorized_disclosure,omitempty"`

	// Signature is the publisher's signature over the canonical form of
	// this report (with Signature itself elided).
	Signature keys.PublicationSignature `json:"signature"`
}

// DisclosureAuthorization is the user's explicit, signed permission to
// include decrypted brief or enclosure content as evidence in an abuse
// report (REPUTATION.md §3.5).
type DisclosureAuthorization struct {
	UserID    string                    `json:"user_id"`
	IssuedAt  time.Time                 `json:"issued_at"`
	Scope     []string                  `json:"scope"` // e.g. ["brief", "enclosure"]
	Signature keys.PublicationSignature `json:"signature"`
}
